import type { PhosphorWeight } from "@/packages/studio-schema/src/types";

export type IconEntry = {
  name: string;
  tags: string[];
  category: string;
};

// Top ~200 most-used Material Symbols for the picker
export const MATERIAL_ICONS: IconEntry[] = [
  // Navigation
  { name: "home", tags: ["house", "main"], category: "Navigation" },
  { name: "menu", tags: ["hamburger", "nav"], category: "Navigation" },
  { name: "close", tags: ["x", "dismiss"], category: "Navigation" },
  { name: "arrow_back", tags: ["left", "previous"], category: "Navigation" },
  { name: "arrow_forward", tags: ["right", "next"], category: "Navigation" },
  { name: "arrow_upward", tags: ["up"], category: "Navigation" },
  { name: "arrow_downward", tags: ["down"], category: "Navigation" },
  { name: "chevron_left", tags: ["back"], category: "Navigation" },
  { name: "chevron_right", tags: ["forward"], category: "Navigation" },
  { name: "expand_more", tags: ["down", "dropdown"], category: "Navigation" },
  { name: "expand_less", tags: ["up", "collapse"], category: "Navigation" },
  { name: "more_horiz", tags: ["dots", "options"], category: "Navigation" },
  { name: "more_vert", tags: ["dots", "options"], category: "Navigation" },

  // Actions
  { name: "search", tags: ["find", "lookup"], category: "Action" },
  { name: "add", tags: ["plus", "create", "new"], category: "Action" },
  { name: "remove", tags: ["minus", "subtract"], category: "Action" },
  { name: "edit", tags: ["pencil", "modify"], category: "Action" },
  { name: "delete", tags: ["trash", "remove"], category: "Action" },
  { name: "check", tags: ["done", "complete", "tick"], category: "Action" },
  { name: "check_circle", tags: ["done", "success"], category: "Action" },
  { name: "settings", tags: ["gear", "preferences"], category: "Action" },
  { name: "refresh", tags: ["reload", "sync"], category: "Action" },
  { name: "download", tags: ["save", "export"], category: "Action" },
  { name: "upload", tags: ["import"], category: "Action" },
  { name: "share", tags: ["send"], category: "Action" },
  { name: "content_copy", tags: ["copy", "duplicate"], category: "Action" },
  { name: "content_paste", tags: ["paste"], category: "Action" },
  { name: "undo", tags: ["back"], category: "Action" },
  { name: "redo", tags: ["forward"], category: "Action" },
  { name: "filter_list", tags: ["sort", "filter"], category: "Action" },
  { name: "sort", tags: ["order"], category: "Action" },
  { name: "print", tags: ["printer"], category: "Action" },
  { name: "save", tags: ["floppy", "disk"], category: "Action" },
  { name: "bookmark", tags: ["save", "favorite"], category: "Action" },
  { name: "favorite", tags: ["heart", "love", "like"], category: "Action" },
  { name: "star", tags: ["rate", "favorite"], category: "Action" },
  { name: "thumb_up", tags: ["like", "approve"], category: "Action" },
  { name: "thumb_down", tags: ["dislike", "reject"], category: "Action" },
  { name: "visibility", tags: ["eye", "show", "view"], category: "Action" },
  { name: "visibility_off", tags: ["hide", "eye"], category: "Action" },
  { name: "lock", tags: ["secure", "private"], category: "Action" },
  { name: "lock_open", tags: ["unlock"], category: "Action" },

  // Communication
  { name: "mail", tags: ["email", "message"], category: "Communication" },
  { name: "call", tags: ["phone", "telephone"], category: "Communication" },
  { name: "chat", tags: ["message", "conversation"], category: "Communication" },
  { name: "forum", tags: ["discussion", "comments"], category: "Communication" },
  { name: "send", tags: ["submit", "email"], category: "Communication" },
  { name: "notifications", tags: ["bell", "alert"], category: "Communication" },
  { name: "campaign", tags: ["megaphone", "announce"], category: "Communication" },

  // Content
  { name: "article", tags: ["document", "text"], category: "Content" },
  { name: "description", tags: ["document", "file"], category: "Content" },
  { name: "image", tags: ["photo", "picture"], category: "Content" },
  { name: "videocam", tags: ["video", "camera"], category: "Content" },
  { name: "play_arrow", tags: ["start", "video"], category: "Content" },
  { name: "pause", tags: ["stop", "hold"], category: "Content" },
  { name: "play_circle", tags: ["start", "video"], category: "Content" },
  { name: "music_note", tags: ["audio", "sound"], category: "Content" },
  { name: "mic", tags: ["microphone", "record"], category: "Content" },
  { name: "photo_camera", tags: ["camera", "snapshot"], category: "Content" },
  { name: "attach_file", tags: ["paperclip", "attachment"], category: "Content" },
  { name: "link", tags: ["url", "chain"], category: "Content" },
  { name: "title", tags: ["heading", "text"], category: "Content" },
  { name: "notes", tags: ["text", "document"], category: "Content" },
  { name: "format_bold", tags: ["bold", "B"], category: "Content" },
  { name: "format_italic", tags: ["italic", "I"], category: "Content" },
  { name: "format_list_bulleted", tags: ["list", "ul"], category: "Content" },
  { name: "format_list_numbered", tags: ["list", "ol"], category: "Content" },
  { name: "format_quote", tags: ["blockquote"], category: "Content" },
  { name: "code", tags: ["programming", "dev"], category: "Content" },

  // People
  { name: "person", tags: ["user", "profile", "account"], category: "People" },
  { name: "group", tags: ["team", "people", "users"], category: "People" },
  { name: "groups", tags: ["community", "people"], category: "People" },
  { name: "person_add", tags: ["add user", "invite"], category: "People" },
  { name: "face", tags: ["emoji", "smile"], category: "People" },
  { name: "diversity_3", tags: ["inclusion", "community"], category: "People" },
  { name: "volunteer_activism", tags: ["help", "hand", "heart"], category: "People" },

  // Places & Maps
  { name: "location_on", tags: ["pin", "map", "place"], category: "Places" },
  { name: "map", tags: ["directions", "navigate"], category: "Places" },
  { name: "church", tags: ["religion", "worship"], category: "Places" },
  { name: "school", tags: ["education", "learning"], category: "Places" },
  { name: "store", tags: ["shop", "business"], category: "Places" },
  { name: "restaurant", tags: ["food", "dining"], category: "Places" },

  // Status & Info
  { name: "info", tags: ["information", "about"], category: "Status" },
  { name: "warning", tags: ["alert", "caution"], category: "Status" },
  { name: "error", tags: ["alert", "danger"], category: "Status" },
  { name: "help", tags: ["question", "faq", "support"], category: "Status" },
  { name: "schedule", tags: ["time", "clock"], category: "Status" },
  { name: "event", tags: ["calendar", "date"], category: "Status" },
  { name: "today", tags: ["calendar", "date"], category: "Status" },
  { name: "trending_up", tags: ["growth", "increase"], category: "Status" },
  { name: "trending_down", tags: ["decline", "decrease"], category: "Status" },

  // Social
  { name: "public", tags: ["globe", "world", "web"], category: "Social" },
  { name: "language", tags: ["globe", "translate"], category: "Social" },
  { name: "share", tags: ["social", "send"], category: "Social" },

  // Layout & Design
  { name: "dashboard", tags: ["overview", "layout"], category: "Layout" },
  { name: "view_module", tags: ["grid", "cards"], category: "Layout" },
  { name: "view_list", tags: ["list", "rows"], category: "Layout" },
  { name: "grid_view", tags: ["grid", "tiles"], category: "Layout" },
  { name: "view_column", tags: ["columns"], category: "Layout" },
  { name: "view_day", tags: ["section", "row"], category: "Layout" },
  { name: "view_stream", tags: ["stack", "vertical"], category: "Layout" },
  { name: "layers", tags: ["stack", "depth"], category: "Layout" },
  { name: "crop", tags: ["resize", "trim"], category: "Layout" },
  { name: "aspect_ratio", tags: ["resize"], category: "Layout" },
  { name: "palette", tags: ["color", "theme", "paint"], category: "Layout" },
  { name: "brush", tags: ["paint", "art"], category: "Layout" },
  { name: "auto_awesome", tags: ["magic", "ai", "sparkle"], category: "Layout" },

  // Devices & Hardware
  { name: "computer", tags: ["desktop", "pc"], category: "Device" },
  { name: "smartphone", tags: ["phone", "mobile"], category: "Device" },
  { name: "tablet", tags: ["ipad"], category: "Device" },
  { name: "keyboard", tags: ["type", "input"], category: "Device" },
  { name: "mouse", tags: ["click", "cursor"], category: "Device" },

  // Files
  { name: "folder", tags: ["directory", "file"], category: "File" },
  { name: "folder_open", tags: ["directory"], category: "File" },
  { name: "insert_drive_file", tags: ["document", "file"], category: "File" },
  { name: "cloud", tags: ["storage", "online"], category: "File" },
  { name: "cloud_upload", tags: ["save", "upload"], category: "File" },
  { name: "cloud_download", tags: ["save", "download"], category: "File" },

  // Shopping
  { name: "shopping_cart", tags: ["buy", "purchase"], category: "Shopping" },
  { name: "payments", tags: ["money", "credit card"], category: "Shopping" },
  { name: "receipt_long", tags: ["invoice", "bill"], category: "Shopping" },
  { name: "local_offer", tags: ["tag", "price", "discount"], category: "Shopping" },

  // Misc
  { name: "lightbulb", tags: ["idea", "tip", "insight"], category: "Misc" },
  { name: "rocket_launch", tags: ["launch", "fast", "startup"], category: "Misc" },
  { name: "celebration", tags: ["party", "confetti"], category: "Misc" },
  { name: "emoji_objects", tags: ["idea", "lightbulb"], category: "Misc" },
  { name: "psychology", tags: ["mind", "brain", "think"], category: "Misc" },
  { name: "handshake", tags: ["deal", "partner", "agree"], category: "Misc" },
  { name: "workspace_premium", tags: ["badge", "award", "prize"], category: "Misc" },
  { name: "verified", tags: ["check", "approved"], category: "Misc" },
  { name: "bolt", tags: ["lightning", "fast", "power"], category: "Misc" },
  { name: "globe", tags: ["world", "earth", "international"], category: "Misc" },
  { name: "eco", tags: ["leaf", "green", "nature"], category: "Misc" },
  { name: "spa", tags: ["wellness", "leaf", "zen"], category: "Misc" },
  { name: "menu_book", tags: ["bible", "book", "read"], category: "Misc" },
  { name: "cross", tags: ["religion", "faith"], category: "Misc" },
];

export const PHOSPHOR_ICONS: IconEntry[] = [
  { name: "house", tags: ["home", "main"], category: "Navigation" },
  { name: "list", tags: ["menu", "hamburger"], category: "Navigation" },
  { name: "x", tags: ["close", "dismiss"], category: "Navigation" },
  { name: "arrow-left", tags: ["back", "previous"], category: "Navigation" },
  { name: "arrow-right", tags: ["forward", "next"], category: "Navigation" },
  { name: "caret-down", tags: ["dropdown", "expand"], category: "Navigation" },
  { name: "caret-up", tags: ["collapse"], category: "Navigation" },
  { name: "dots-three", tags: ["more", "options"], category: "Navigation" },
  { name: "magnifying-glass", tags: ["search", "find"], category: "Action" },
  { name: "plus", tags: ["add", "create"], category: "Action" },
  { name: "minus", tags: ["remove", "subtract"], category: "Action" },
  { name: "pencil-simple", tags: ["edit", "write"], category: "Action" },
  { name: "trash", tags: ["delete", "remove"], category: "Action" },
  { name: "check", tags: ["done", "complete"], category: "Action" },
  { name: "check-circle", tags: ["done", "success"], category: "Action" },
  { name: "gear", tags: ["settings", "preferences"], category: "Action" },
  { name: "arrows-clockwise", tags: ["refresh", "reload"], category: "Action" },
  { name: "download-simple", tags: ["save", "export"], category: "Action" },
  { name: "upload-simple", tags: ["import"], category: "Action" },
  { name: "share-network", tags: ["share", "send"], category: "Action" },
  { name: "copy", tags: ["duplicate", "content-copy"], category: "Action" },
  { name: "clipboard", tags: ["paste"], category: "Action" },
  { name: "heart", tags: ["favorite", "love", "like"], category: "Action" },
  { name: "star", tags: ["rate", "favorite"], category: "Action" },
  { name: "eye", tags: ["visibility", "show"], category: "Action" },
  { name: "eye-slash", tags: ["hide", "invisible"], category: "Action" },
  { name: "lock-simple", tags: ["secure", "private"], category: "Action" },
  { name: "lock-simple-open", tags: ["unlock"], category: "Action" },
  { name: "bookmark-simple", tags: ["save"], category: "Action" },
  { name: "envelope-simple", tags: ["mail", "email"], category: "Communication" },
  { name: "phone", tags: ["call", "telephone"], category: "Communication" },
  { name: "chat-circle", tags: ["message", "bubble"], category: "Communication" },
  { name: "paper-plane-tilt", tags: ["send", "submit"], category: "Communication" },
  { name: "bell", tags: ["notification", "alert"], category: "Communication" },
  { name: "megaphone", tags: ["announce", "campaign"], category: "Communication" },
  { name: "image", tags: ["photo", "picture"], category: "Content" },
  { name: "video-camera", tags: ["video", "film"], category: "Content" },
  { name: "play", tags: ["start", "video"], category: "Content" },
  { name: "pause", tags: ["stop", "hold"], category: "Content" },
  { name: "music-note", tags: ["audio", "sound"], category: "Content" },
  { name: "microphone", tags: ["record", "voice"], category: "Content" },
  { name: "camera", tags: ["photo", "snapshot"], category: "Content" },
  { name: "paperclip", tags: ["attach", "file"], category: "Content" },
  { name: "link", tags: ["url", "chain"], category: "Content" },
  { name: "text-aa", tags: ["typography", "font"], category: "Content" },
  { name: "code", tags: ["programming", "dev"], category: "Content" },
  { name: "user", tags: ["person", "profile", "account"], category: "People" },
  { name: "users", tags: ["group", "team", "people"], category: "People" },
  { name: "user-plus", tags: ["add user", "invite"], category: "People" },
  { name: "smiley", tags: ["emoji", "face", "happy"], category: "People" },
  { name: "hands-clapping", tags: ["applause", "celebrate"], category: "People" },
  { name: "map-pin", tags: ["location", "place"], category: "Places" },
  { name: "globe-hemisphere-west", tags: ["world", "earth"], category: "Places" },
  { name: "buildings", tags: ["city", "office"], category: "Places" },
  { name: "cross", tags: ["church", "religion", "faith"], category: "Places" },
  { name: "info", tags: ["information", "about"], category: "Status" },
  { name: "warning", tags: ["alert", "caution"], category: "Status" },
  { name: "warning-circle", tags: ["error", "danger"], category: "Status" },
  { name: "question", tags: ["help", "faq"], category: "Status" },
  { name: "clock", tags: ["time", "schedule"], category: "Status" },
  { name: "calendar", tags: ["date", "event"], category: "Status" },
  { name: "trend-up", tags: ["growth", "increase"], category: "Status" },
  { name: "trend-down", tags: ["decline", "decrease"], category: "Status" },
  { name: "squares-four", tags: ["grid", "dashboard"], category: "Layout" },
  { name: "rows", tags: ["list", "horizontal"], category: "Layout" },
  { name: "columns", tags: ["layout", "vertical"], category: "Layout" },
  { name: "stack", tags: ["layers", "depth"], category: "Layout" },
  { name: "palette", tags: ["color", "theme", "paint"], category: "Layout" },
  { name: "paint-brush", tags: ["brush", "art"], category: "Layout" },
  { name: "sparkle", tags: ["magic", "ai", "stars"], category: "Layout" },
  { name: "lightning", tags: ["bolt", "fast", "power"], category: "Misc" },
  { name: "rocket", tags: ["launch", "startup"], category: "Misc" },
  { name: "confetti", tags: ["celebrate", "party"], category: "Misc" },
  { name: "lightbulb", tags: ["idea", "tip"], category: "Misc" },
  { name: "brain", tags: ["mind", "think", "ai"], category: "Misc" },
  { name: "handshake", tags: ["deal", "partner"], category: "Misc" },
  { name: "medal", tags: ["award", "badge", "prize"], category: "Misc" },
  { name: "seal-check", tags: ["verified", "approved"], category: "Misc" },
  { name: "leaf", tags: ["eco", "nature", "green"], category: "Misc" },
  { name: "book-open", tags: ["read", "bible", "study"], category: "Misc" },
  { name: "shopping-cart", tags: ["buy", "purchase"], category: "Shopping" },
  { name: "credit-card", tags: ["payment", "money"], category: "Shopping" },
  { name: "receipt", tags: ["invoice", "bill"], category: "Shopping" },
  { name: "tag", tags: ["price", "label", "discount"], category: "Shopping" },
  { name: "folder-simple", tags: ["directory", "file"], category: "File" },
  { name: "file", tags: ["document"], category: "File" },
  { name: "cloud", tags: ["storage", "online"], category: "File" },
];

export const PHOSPHOR_WEIGHTS: PhosphorWeight[] = [
  "thin",
  "light",
  "regular",
  "bold",
  "fill",
  "duotone",
];

export function getAllIcons(lib: "material" | "phosphor"): IconEntry[] {
  return lib === "material" ? MATERIAL_ICONS : PHOSPHOR_ICONS;
}

export function getIconCategories(lib: "material" | "phosphor"): string[] {
  const icons = getAllIcons(lib);
  return [...new Set(icons.map((i) => i.category))];
}
